routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\HomeController;
use App\Http\Controllers\Dashboard\Auth\LoginController;
use App\Http\Controllers\Dashboard\AdminController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\GovernorateController;
use App\Http\Controllers\Dashboard\CountryController;
use App\Http\Controllers\Dashboard\CouponController;
use App\Http\Controllers\Dashboard\PageController;
use App\Http\Controllers\Dashboard\SlideController;
use App\Http\Controllers\Dashboard\SiteInfoController;
use App\Http\Controllers\Dashboard\ProfileController;
use App\Http\Controllers\Dashboard\ShippingCompanyController;
use App\Http\Controllers\Dashboard\BrandController;
use App\Http\Controllers\Dashboard\ProductController;
use App\Http\Controllers\Dashboard\ProductImageController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\MessageController;

use App\Http\Controllers\Site\Auth\GoogleAuthController;
use App\Http\Controllers\Site\Auth\FacebookAuthController;
use App\Http\Controllers\Site\User\AccountController;
use App\Http\Controllers\Site\HomeController As SiteHomeController;
use App\Http\Controllers\Site\ContactUsController;
use App\Http\Controllers\Site\CartController;
use App\Http\Controllers\Site\CheckoutController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale() , 
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'
    ] ], function()
    {

        Route::get('/dashboard', function () {
            return view('dashboard');
        })->middleware(['auth'])->name('dashboard');
        require __DIR__.'/auth.php';

        Route::get('/Dashboard/login', [LoginController::class , 'form'])->name('dashboard.login.form');
        Route::post('/Dashboard/login', [LoginController::class , 'login'])->name('dashboard.login');
        Route::group(['prefix' => 'Dashboard' , 'as' => 'dashboard.' , 'middleware' => ['admin'] ], function() {
            Route::get('/' , [HomeController::class , 'index'])->name('home');
            Route::resource('admins', AdminController::class);
            Route::resource('categories', CategoryController::class);
            Route::resource('countries', CountryController::class);
            Route::resource('governorates', GovernorateController::class);
            Route::resource('coupons', CouponController::class);
            Route::resource('pages', PageController::class);
            Route::resource('brands', BrandController::class);
            Route::resource('orders', OrderController::class);
            Route::resource('products', ProductController::class);
            Route::resource('messages', MessageController::class);
            Route::get('product_images.destroy', [ProductImageController::class , 'destroy' ])->name('product_images.destroy');
            Route::resource('shipping_companies', ShippingCompanyController::class);
            Route::resource('slides', SlideController::class);
            Route::resource('slides', SlideController::class);
            Route::get('/site_info' , [SiteInfoController::class , 'edit'])->name('site_info.edit');
            Route::patch('/site_info' , [SiteInfoController::class , 'update'])->name('site_info.update');
            Route::get('/logout' ,  [LoginController::class , 'logout'])->name('logout');
            Route::get('/profile' ,  [ProfileController::class , 'profile'])->name('profile');
            Route::patch('/profile' ,  [ProfileController::class , 'update_profile'])->name('profile.update');

            Route::get('/password' ,  [ProfileController::class , 'password'])->name('password');
            Route::patch('/password' ,  [ProfileController::class , 'update_password'])->name('password.update');
        });


        Route::get('/auth/google' , [GoogleAuthController::class , 'index'] );
        Route::get('/auth/google/callback', [GoogleAuthController::class , 'handleGoogleCallback']);
        Route::get('/auth/facebook' , [FacebookAuthController::class , 'index'] );
        Route::get('/auth/facebook/callback', [FacebookAuthController::class , 'handleFacebookCallback']);


        Route::group(['middleware' => 'auth'], function() {
            Route::get('/account' , [AccountController::class , 'index'])->name('account');
            Route::patch('/account' , [AccountController::class , 'update'])->name('account.update');
            Route::get('/logout' , [AccountController::class , 'logout'])->name('user.logout');
            Route::get('/orders' , [AccountController::class , 'logout'])->name('user.orders');
        });



        Route::group(['middleware' => ['cart' , 'country'] ], function() {
            Route::get('/' , [SiteHomeController::class , 'index'] );
            Route::get('/p/{product}' , [SiteHomeController::class , 'product'] )->name('products.show');
            Route::get('/contact' , [ContactUsController::class , 'form'] )->name('contact.form');
            Route::post('/send' , [ContactUsController::class , 'send'] )->name('contact.send');
            Route::post('/cart'  , [CartController::class , 'store'] )->name('cart.store');
            Route::get('/cart'  , [CartController::class , 'index'] )->name('cart.index');
            Route::get('/shop/{category}' , [SiteHomeController::class , 'category_products'] )->name('category.products');
            Route::get('/shop' ,  [SiteHomeController::class , 'shop']  )->name('shop');
            Route::get('/page/{page}' ,  [SiteHomeController::class , 'page']  )->name('pages.show');
            Route::get('/checkout' , [CheckoutController::class , 'show'] )->name('checkout.show');
            Route::post('/checkout' , [CheckoutController::class , 'store'] )->name('checkout.store');
            Route::get('/checkout/success' , [CheckoutController::class , 'index'] )->name('checkout.index');
            Route::get('/coupon' , [CheckoutController::class , 'validateDiscountCoupon'] )->name('coupons.validate');
            Route::get('/get_product_details' , [SiteHomeController::class  , 'get_product_details'] )->name('get_product_details');
        });


        
    });

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Dashboard\Admins\StoreAdminRequest;
use App\Http\Requests\Dashboard\Admins\UpdateAdminRequest;
use App\Models\Admin;
use Storage;
class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.admins.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.admins.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminRequest $request)
    {
        $admin = new Admin;
        if(!$admin->add($request->all()))
            return back()->with('error' , trans('admins.adding_error'));

        if($request->hasFile('image')) {
            $image = $request->file('image')->store('admins');
            $admin->image = basename($image);
            $admin->save();
        }
        return redirect(route('dashboard.admins.index'))->with('success'  , trans('admins.adding_success') );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        return view('dashboard.admins.show' , compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $admin)
    {
        return view('dashboard.admins.edit',  compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdminRequest $request,Admin $admin)
    {
        if(!$admin->edit($request->all()))
            return back()->with('error' , trans('admins.editing_error'));

        if($request->hasFile('image')) {
            Storage::delete(['admins/'.$admin->image]);
            $image = $request->file('image')->store('admins');
            $admin->image = basename($image);
            $admin->save();
        }
        return redirect(route('dashboard.admins.index'))->with('success'  , trans('admins.editing_success') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/BrandController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Brand;
use Storage;
use App\Http\Requests\Dashboard\Brands\StoreBrandRequest;
use App\Http\Requests\Dashboard\Brands\UpdateBrandRequest;
class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.brands.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.brands.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBrandRequest $request)
    {
        $brand = new Brand;
        if(!$brand->add($request->all()))
            return back()->with('error' , trans('brands.adding_error'));

        if($request->hasFile('image')) {
            $image = $request->file('image')->store('brands');
            $brand->image = basename($image);
            $brand->save();
        }

        return redirect(route('dashboard.brands.index'))->with('success' , trans('brands.adding_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        return view('dashboard.brands.show' , compact('brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        return view('dashboard.brands.edit' , compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        

        if(!$brand->edit($request->all()))
            return back()->with('error' , trans('brands.editing_error'));

        if($request->hasFile('image')) {
            Storage::delete('brands/'.$brand->image);
            $image = $request->file('image')->store('brands');
            $brand->image = basename($image);
            $brand->save();
        }

        return redirect(route('dashboard.brands.index'))->with('success' , trans('brands.editing_success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use Storage;
use App\Http\Requests\Dashboard\Categories\StoreCategoryRequest;
use App\Http\Requests\Dashboard\Categories\UpdateCategoryRequest;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('category_id' , '=' , null )->get();
        return view('dashboard.categories.create' , compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $category = new Category;
        if(!$category->add($request->all()))
            return back()->with('error' , trans('categories.adding_error') );

        if($request->hasFile('category_image')) {
            $category_image = $request->file('category_image')->store('categories');
            $category->image = basename($category_image);
            $category->save();
        }
        if($request->hasFile('cover')) {
            $cover = $request->file('cover')->store('categories');
            $category->cover = basename($cover);
            $category->save();
        }

        if($request->hasFile('icon')) {
            $icon = $request->file('icon')->store('categories');
            $category->icon = basename($icon);
            $category->save();
        }

        return redirect(route('dashboard.categories.index'))->with('success' , trans('categories.adding_success') );

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $category->load(['category'  , 'admin' ]);
        return view('dashboard.categories.show' , compact('category') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::where('category_id' , '=' , null )->get();
        return view('dashboard.categories.edit' , compact('categories' , 'category') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request,Category $category)
    {
         if(!$category->edit($request->all()))
            return back()->with('error' , trans('categories.editing_error') );

        if($request->hasFile('category_image')) {
            Storage::delete('categories/'.$category->image);
            $category_image = $request->file('category_image')->store('categories');
            $category->image = basename($category_image);
            $category->save();
        }
        if($request->hasFile('cover')) {
            Storage::delete('categories/'.$category->cover);
            $cover = $request->file('cover')->store('categories');
            $category->cover = basename($cover);
            $category->save();
        }

        if($request->hasFile('icon')) {
            Storage::delete('categories/'.$category->icon);
            $icon = $request->file('icon')->store('categories');
            $category->icon = basename($icon);
            $category->save();
        }

        return redirect(route('dashboard.categories.index'))->with('success' , trans('categories.editing_success') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Livewire/Dashboard/Admins/ListAllAdmins.php
<?php

namespace App\Http\Livewire\Dashboard\Admins;

use Livewire\Component;
use App\Models\Admin;
use Storage;
use Livewire\WithPagination;
class ListAllAdmins extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search = '';
    public $rows = 10;

    public function updatedRows()
    {
        $this->resetPage();
    }

    public function updatedSearch()
    {
        $this->resetPage();
    }

    protected $listeners = ['deleteItem'];

    public function deleteItem($id)
    {
        $admin = Admin::find($id);
        $this->resetPage();

        if($admin) {
            Storage::delete('admins/'.$admin->image);
            $admin->delete();
        }
        $this->emit('itemDeleted');
    }


    public function render()
    {
        $admins = Admin::query()->with('admin');

        if($this->search != '')
            $admins = $admins->where('username',  'like' , '%'.$this->search.'%')->orWhere('email',  'like' , '%'.$this->search.'%');


        $admins = $admins->latest()->paginate($this->rows);
        return view('livewire.dashboard.admins.list-all-admins' , compact('admins'));
    }
}

resources/views/livewire/dashboard/governorates/list-all-governorates.blade.php
@php

$lang = LaravelLocalization::getCurrentLocale();
@endphp
<div>
    <div class="col-12">
          @include('dashboard.layouts.messages')
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h3 class="card-title "> @lang('governorates.governorates') </h3>
            </div>
            <div class="card-body border-bottom py-3">
                <div class="d-flex">
                    <div class="">
                        @lang('governorates.rows')
                        <div class="mx-2 d-inline-block">
                            <select wire:model="rows" id="inputWire" class="form-control" required="required">
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="50">50</option>
                                <option value="70">70</option>
                                <option value="100">100</option>
                                <option value="150">150</option>
                            </select>
                        </div>
                     
                    </div>
                    <div class="ms-auto">
                        @lang('governorates.search'):
                        <div class="ms-2 d-inline-block">
                            <input type="text" class="form-control " wire:model="search">
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table card-table table-vcenter text-nowrap datatable">
                    <thead>
                        <tr>
                            <th>@lang('governorates.name_ar')</th>
                            <th>@lang('governorates.name_en')</th>
                            <th>@lang('governorates.country')</th>
                            <th>@lang('governorates.added_by')</th>
                            <th>@lang('governorates.status')</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($governorates as $governorate)
                        <tr>
                            <td>
                                <a href="{{ route('dashboard.governorates.show' , ['governorate' => $governorate->id ]) }}" > {{ $governorate->getTranslation('name' , 'ar') }} </a>
                            </td>
                            <td> {{ $governorate->getTranslation('name' , 'en') }} </td>

                            <td> <a href="{{ route('dashboard.countries.show' , ['country' => $governorate->country_id ] ) }}"> {{ optional($governorate->country)->getTranslation('name' , $lang) }} </a> </td>
                             <td> <a href="{{ route('dashboard.admins.show' , ['admin' => $governorate->admin_id ] ) }}"> {{ optional($governorate->admin)->username }} </a> </td>
                            <td>
                                @switch($governorate->active)
                                @case(1)
                                <span class="badge bg-green">@lang('governorates.active')</span>
                                @break
                                @case(0)
                                <span class="badge bg-red">@lang('governorates.inactive')</span>
                                @break
                                @endswitch
                            </td>

                            <td class="text-end">
                                <div class="btn-list justify-content-center">
                                    <a href="{{ route('dashboard.governorates.edit' , ['governorate' => $governorate->id ] ) }}" class="btn btn-warning btn-sm">
                                        <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 0px;" class="icon icon-tabler icon-tabler-pencil" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4"></path>
                                            <line x1="13.5" y1="6.5" x2="17.5" y2="10.5"></line>
                                        </svg>
                                    </a>

                                    <a data-item_id="{{ $governorate->id }}"  class="btn btn-danger btn-sm delete_item">
                                        <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 0px;" class="icon icon-tabler icon-tabler-trash" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <line x1="4" y1="7" x2="20" y2="7"></line>
                                            <line x1="10" y1="11" x2="10" y2="17"></line>
                                            <line x1="14" y1="11" x2="14" y2="17"></line>
                                            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                                            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
                                        </svg>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer d-flex align-items-center">
                <p class="m-0 text-muted"> <span>{{ $governorates->perPage() }}</span> of <span>{{ $governorates->total() }}</span> entries</p>

                <div class="m-0 ms-auto">
                    {{ $governorates->links() }}
                </div>

            </div>
        </div>
    </div>
</div>


@section('scripts')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(function() {

        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })
        Livewire.on('itemDeleted', postId => {
            Toast.fire({
              icon: 'success',
              title: "@lang('governorates.deleting_success')"
          })
        })
        $(document).on('click', 'a.delete_item', function(event) {
            event.preventDefault();
            var item_id = $(this).attr('data-item_id');
            Swal.fire({
                title: '@lang('governorates.confirmation_delete_message')',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '@lang('governorates.yes')',
                cancelButtonText: '@lang('governorates.back')',
            }).then((result) => {
                if (result.isConfirmed) {
                    Livewire.emit('deleteItem' , item_id);
                }
            })

        });
    });
</script>

@endsection